-- What is the total revenue for each mall? 

WITH sales_per_mall AS (
    SELECT
        shopping_mall,
        SUM(s.quantity * s.price) AS total_sales
	FROM
        sales_data s
    GROUP BY
        shopping_mall)
		
    SELECT
        shopping_mall,
        total_sales,
        RANK() OVER (ORDER BY total_sales DESC) AS rank_desc
    FROM
        sales_per_mall

-- What is the average revenue per customer for each mall?

	SELECT
        s.shopping_mall,
        (SUM(s.quantity * s.price)/COUNT(s.customer_id)) AS total_sales_per_customer
    FROM
        sales_data s
    GROUP BY
        shopping_mall

-- What are the top 3 and the bottom 3 shopping malls based on total sales?

WITH sales_per_mall AS (
    SELECT
        shopping_mall,
        SUM(s.quantity * s.price) AS total_sales
    FROM
        sales_data s
    GROUP BY
        shopping_mall
),
ranked_malls AS (
    SELECT
        shopping_mall,
        total_sales,
        RANK() OVER (ORDER BY total_sales DESC) AS rank_desc
    FROM
        sales_per_mall
)
SELECT
    s.shopping_mall,
    c.gender,
    COUNT(*) AS gender_count,
	ranked_malls.rank_desc
FROM
    sales_data s
	JOIN customer_data c ON s.customer_id = c.customer_id
	JOIN ranked_malls ON s.shopping_mall = ranked_malls.shopping_mall
GROUP BY
    s.shopping_mall,
    c.gender,
	ranked_malls.rank_desc
ORDER BY
    ranked_malls.rank_desc,
	c.gender;

-- What is the total revenue generated by each shopping mall, categorized by payment method?

SELECT
    shopping_mall,
    payment_method,
    SUM(quantity * price) AS revenue_per_payment_method
FROM sales_data s
LEFT JOIN customer_data c ON s.customer_id = c.customer_id
GROUP BY
    shopping_mall,
    payment_method

-- What is the total revenue per gender in the top three shopping malls?

WITH top_malls AS ( 
    SELECT
        shopping_mall,
        ROUND(SUM(quantity * price)) AS revenue_per_mall
    FROM 
        sales_data
    GROUP BY 
        shopping_mall
    ORDER BY 
        revenue_per_mall DESC
    LIMIT 
        3)

SELECT
    tm.shopping_mall,
    c.gender,
    SUM(s.quantity * s.price) as revenue_per_gender
FROM
    top_malls tm
LEFT JOIN sales_data s on tm.shopping_mall = s.shopping_mall
LEFT JOIN customer_data c on s.customer_id = c.customer_id
GROUP BY
    tm.shopping_mall,
    c.gender
ORDER BY
    tm.shopping_mall,
    revenue_per_gender DESC

-- Age Group Distribution (Average Spending Per Age Group):

SELECT
    AVG(s.quantity * s.price) AS avg_spending,
    CASE 
        WHEN c.age BETWEEN 0 AND 17 THEN 'Under 18'
        WHEN c.age BETWEEN 18 AND 24 THEN '18-24'
        WHEN c.age BETWEEN 25 AND 34 THEN '25-34'
        WHEN c.age BETWEEN 35 AND 49 THEN '35-49'
        WHEN c.age BETWEEN 50 AND 64 THEN '50-64'
        ELSE 'Over 65'
    END AS age_groups
FROM
    sales_data s
INNER JOIN customer_data c ON s.customer_id = c.customer_id
GROUP BY
    age_groups
ORDER BY
	avg_spending DESC

-- What are the differences among the three top and three bottom shopping malls in terms of sales revenue?

WITH mall_rev_category AS 
(SELECT
    shopping_mall,
    category,
    ROUND(SUM(quantity * price)) AS revenue_per_cat
FROM 
    sales_data
GROUP BY 
    shopping_mall, 
    category
ORDER BY 
    shopping_mall),
    
ranked_malls AS (
    SELECT
        shopping_mall,
        SUM(revenue_per_cat) AS total_mall_revenue,
        RANK() OVER (ORDER BY SUM(revenue_per_cat) DESC) AS mall_rank
    FROM mall_rev_category
    GROUP BY shopping_mall)

SELECT 
    rc.category,
    rc.revenue_per_cat,
    rc.shopping_mall
FROM 
    mall_rev_category rc 
LEFT JOIN ranked_malls rm ON rc.shopping_mall = rm.shopping_mall
WHERE
    rm.mall_rank <= 3
ORDER BY 
    rm.mall_rank, 
    rc.revenue_per_cat DESC;

-- What is the percentage distribution of gender across payment methods and shopping malls?

WITH top_malls AS (
    SELECT
        shopping_mall,
        ROUND(SUM(quantity * price)) AS revenue_per_mall
    FROM 
        sales_data
    GROUP BY 
        shopping_mall
    ORDER BY 
        revenue_per_mall DESC
    LIMIT 
        3)

SELECT
    tm.shopping_mall,
    c.gender,
    SUM(s.quantity * s.price) as revenue_per_gender,
    ROUND(100.0 * SUM(s.quantity * s.price) / SUM(SUM(s.quantity * s.price)) OVER (PARTITION BY tm.shopping_mall), 2) AS gender_percentage
FROM
    top_malls tm
LEFT JOIN sales_data s on tm.shopping_mall = s.shopping_mall
LEFT JOIN customer_data c on s.customer_id = c.customer_id
GROUP BY
    tm.shopping_mall,
    c.gender
ORDER BY
    tm.shopping_mall,
    revenue_per_gender
	
-- Scenario: 
-- Assuming these malls are owned by the same company with a year target , which malls reached this target and in what order? 

SELECT 
	shopping_mall,
	invoice_date,
	s.quantity * s.price AS total_sales,
	SUM(s.quantity * s.price) OVER (PARTITION BY shopping_mall ORDER BY invoice_no) AS running_total,
	invoice_no
FROM
	sales_data s
WHERE
	 EXTRACT(YEAR FROM invoice_date) = 2023
ORDER BY
	shopping_mall